Repository Icinga/ipl-stdlib, pull requests merged in 2023-08, with the labels that each got.

#40 Github Actions: Add Phpstan
  .github/workflows/php.yml
  phpstan-baseline.neon
  phpstan.neon
  src/Contract/Validator.php
  src/Data.php
  src/Filter.php
  src/Filter/Chain.php
  src/PriorityQueue.php
  src/Seq.php
  src/Str.php
  src/functions.php
Labels: cla/signed

#47 PHPStan: Ignore errors which we do not treat as errors
  phpstan.neon
Labels: cla/signed

#45 Str: Also return padded array in case subject is null
  src/Str.php
  tests/StrTest.php
Labels: bug, cla/signed

#48 Github Actions: Do not cancel further tests if one fails
  .github/workflows/php.yml
Labels: cla/signed

#46 Introduce `yield_groups()`
  src/functions.php
  tests/FunctionsTest.php
Labels: enhancement, cla/signed
